### ISSUE TITLE
Unhandled project rejections

### ISSUE THREAD

**Issue by krzkaczor** [fathyb/parcel-plugin-typescript#11]
I am getting lots of these errors. Even though the project is built correctly Oo:

```
(node:54404) UnhandledPromiseRejectionWarning: Error: Error: Error: Could not find file: '/Users/krzkaczor/project/workspace/project/app/components/App.tsx'.
    at getValidSourceFile (/Users/krzkaczor/project/workspace/project/node_modules/typescript/lib/typescript.js:95642:23)
    at Object.getSemanticDiagnostics (/Users/krzkaczor/project/workspace/project/node_modules/typescript/lib/typescript.js:95824:36)
    at LanguageService.check (/Users/krzkaczor/project/workspace/project/node_modules/parcel-plugin-typescript/build/backend/service/index.js:14:41)
    at Object.<anonymous> (/Users/krzkaczor/project/workspace/project/node_modules/parcel-plugin-typescript/build/backend/worker/launcher.js:34:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/krzkaczor/project/workspace/project/node_modules/tslib/tslib.js:102:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at TypeScriptWorker.<anonymous> (/Users/krzkaczor/project/workspace/project/node_modules/parcel-plugin-typescript/build/ipc/worker/index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/krzkaczor/project/workspace/project/node_modules/tslib/tslib.js:102:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at /Users/krzkaczor/project/workspace/project/node_modules/parcel-plugin-typescript/build/ipc/client.js:15:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/krzkaczor/project/workspace/project/node_modules/tslib/tslib.js:102:62)
    at <anonymous>
(node:54404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:54404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejecti```

**Comment by fathyb** [comment]
Do you have a reproduction repository? It'll help me figure out what's going on.

**Comment by krzkaczor** [comment]
@fathyb I fixed it, sorry to bother you. It happened because the file that I wanted to include wasn't matched by include glob in `tsconfig.json`. 

The error message could be clearer though. I will try to contribute and fix it.

**Comment by fathyb** [comment]
Oh I see, you're right the message should be clearer. No problem thanks for contributing!
