### ISSUE TITLE
"Error: Cannot find source file" when building on Windows

### ISSUE THREAD

**Issue by severisv** [fathyb/parcel-plugin-typescript#26]
package.json:
```
{
  "name": "index",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "build": "parcel build index.html"
  },
  "devDependencies": {
    "@types/react": "^16.0.37",
    "@types/react-dom": "^16.0.4",
    "autoprefixer": "^8.0.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.5.1",
    "parcel-plugin-typescript": "^0.6.0",
    "typescript": "^2.7.1"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

index.html:
```
<html>
<body>
    <div id="root"></div>
    <script src="./Index.tsx"></script>
</body>
</html
```

tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "es2015", "es2016", "es2017.object"],
    "jsx": "preserve",
    "target": "es2017",
    "module": "es2015",
    "moduleResolution": "node",
    "strict": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "baseUrl": ".",
    "paths": {
      "*": ["*"]
    }
  },
  "parcelTsPluginOptions": {
    "transpileOnly": false
  }
}
```

.babelrc
```
{
    "presets": ["env", "react"]
 }
```

Index.tsx:
```
import React from "react";
import ReactDOM from "react-dom";

const App = () => <div>Hello World!</div>;

ReactDOM.render(<App />, document.getElementById("root"));
```

Running: `parcel build index.html` results in following error:

```
 Error: Error: Error: Cannot find source file "C:\projects\parcel-ts\Index.tsx"
    at TypeScriptCompiler.compile (C:\projects\parcel-ts\node_modules\parcel-plugin-typescript\build\backend\compiler\tsc.js:25:19)
    at Object.<anonymous> (C:\projects\parcel-ts\node_modules\parcel-plugin-typescript\build\backend\worker\launcher.js:28:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\projects\parcel-ts\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at TypeScriptWorker.<anonymous> (C:\projects\parcel-ts\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\projects\parcel-ts\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\projects\parcel-ts\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by severisv** [comment]
Note that removing `parcel-plugin-typescript` from `package.json` causes project to compile just fine

**Comment by fathyb** [comment]
Does it work if you add `include` to your `tsconfig.json`? eg. :
```js
{
  "compileOnSave": false,
  "compilerOptions": { ... },
  "parcelTsPluginOptions": { ... },
  "include": [
     "**/*.ts",
     "**/*.tsx"
   ]
}
```

This may be related to #11.

**Comment by severisv** [comment]
Nope :/

**Comment by Vitegor** [comment]
+1

**Comment by lednhatkhanh** [comment]
I'm having the exact same bug, have to remove parcel-plugin-typescript for now...

**Comment by msokk** [comment]
I'm on macOS and getting a bit different error:
```
🚨  Error: Error: Error: Cannot find virtual file "/Users/mihkel/Projects/atelier_resellers/src/index.tsx"
    at TypeScriptCompiler.compile (/Users/mihkel/Projects/atelier_resellers/node_modules/parcel-plugin-typescript/build/backend/compiler/tsc.js:36:19)
```

Same error pops up on next ts/tsx file when converting entry file to js.

**Comment by msokk** [comment]
Changing `jsx` tsconfig value from `preserve` to `react` fixed it for me.

**Comment by fathyb** [comment]
Sorry for delay and good catch @msokk!

I published `parcel-plugin-typescript@0.6.1-next.0` on npm to fix this. Could you guys try it and confirm me it works for you?

**Comment by Vitegor** [comment]
@fathyb, my case after update package to `parcel-plugin-typescript@0.6.1-next.0`:

- **files**
src
-- index.html
-- index.ts
package.json
tsconfig.json

- **index.html**

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hello, Vue & Parcel</title>
    </head>
    <body>
        <div id="app"></div>
        <script src="./index.ts"></script>
    </body>
</html>
```

- **index.ts**

```
var getMessage = (name: string): string => {
    return `Hello, ${name}!`;
}
console.log(getMessage(12345));
```

- tsconfig.json

```
{
  "parcelTsPluginOptions": {
    "transpileOnly": false
  }
}
```

- **package.json**
```
...
"scripts": {
    "dev": "parcel src/index.html --open --no-cache",
    "build": "parcel build src/index.html --no-minify --no-cache --public-url ./",
    "prod": "parcel build src/index.html  --no-cache --public-url ./"
  }
...
```
--
**npm run dev** result:

```
�  D:/dev/_tests/parcel_vue/src/index.ts(36,24)
Argument of type '12345' is not assignable to parameter of type 'string'.
    35 |
  > 36 | console.log(getMessage(12345));
       |                        ^^^^^
    37 |
```
yes, i get error, but code is complied, and i can see result in browser console: `Hello, 12345!`

--
**npm run build** result
```
Error: Error: Error: Cannot find source file "D:\dev\_tests\parcel_vue\src\index.ts"
    at TypeScriptCompiler.compile (D:\dev\_tests\parcel_vue\node_modules\parcel-plugin-typescript\build\backend\compiler\tsc.js:25:19)
    at Object.<anonymous> (D:\dev\_tests\parcel_vue\node_modules\parcel-plugin-typescript\build\backend\worker\launcher.js:28:29)
    at Generator.next (<anonymous>)
    at fulfilled (D:\dev\_tests\parcel_vue\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at TypeScriptWorker.<anonymous> (D:\dev\_tests\parcel_vue\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (D:\dev\_tests\parcel_vue\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (D:\dev\_tests\parcel_vue\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR! code ELIFECYCLEback (internal/process/next_tick.js:180:9)
```

**Comment by severisv** [comment]
I tried the new version, and it doesn't change anything for me.

Note that `parcel watch ./src/index.html -d ../server/wwwroot/dist --public-url /dist` works fine, but `parcel build ./src/index.html -d ../server/wwwroot/dist --public-url /dist` does not work (same stack trace as before). This was the case with the previous version (0.6.0) aswell - watch worked, but not build.

**Comment by fathyb** [comment]
@severisv and @Vitegor : I confirm that I'm able to reproduce your bug. It only happens on Windows though.

Could you try `parcel-plugin-typescript@0.6.1-next.2`? I tested it on Windows 10 with both of your reproductions and it works. If it doesn't please check if you have the right version using `yarn list` or `npm ls`.

**Comment by Vitegor** [comment]
@fathyb, after update to `parcel-plugin-typescript@0.6.1-next.2`  works, thanks

**Comment by severisv** [comment]
I can confirm that it works for me aswell. Thank you!

**Comment by jesnil01** [comment]
I have a problem with build "Error: Error: Error: Cannot find virtual file [my-file-path]/src/components/Breadcrumbs/index.js" 

Is this related or should I create a seperate issue? Does not work for me with parcel-plugin-typescript@0.6.1-next.2

**Comment by fathyb** [comment]
[`0.6.1` and `0.7.0` released](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/CHANGELOG.md#070-2018-02-28) with the fix.

@jesnil01 could you open an issue with a repro?
