### ISSUE TITLE
Throwing errors

### ISSUE THREAD

**Issue by samdenty** [fathyb/parcel-plugin-typescript#38]
After installing this package and starting parcel, it throws errors about missing files. These files definitely exist
Typescript version: 2.8.3 / 3.0.0

```
(node:27724) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Error: Error: Could not find file: 'D:\Data\Drive\Github\widgetbot2\packages\crate\src\index.tsx'.
    at getValidSourceFile (D:\Data\Drive\Github\widgetbot2\packages\crate\node_modules\typescript\lib\typescript.js:107364:23)
    at Object.getSemanticDiagnostics (D:\Data\Drive\Github\widgetbot2\packages\crate\node_modules\typescript\lib\typescript.js:107560:36)
    at LanguageService.check (D:\Data\Drive\Github\widgetbot2\packages\crate\node_modules\parcel-plugin-typescript\build\backend\service\index.js:15:24)
    at Object.<anonymous> (D:\Data\Drive\Github\widgetbot2\packages\crate\node_modules\parcel-plugin-typescript\build\backend\worker\launcher.js:34:28)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Data\Drive\Github\widgetbot2\packages\crate\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at TypeScriptWorker.<anonymous> (D:\Data\Drive\Github\widgetbot2\packages\crate\node_modules\parcel-plugin-typescript\build\backend\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Data\Drive\Github\widgetbot2\packages\crate\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by samdenty** [comment]
This seems to be because the files weren't included in the `paths`, is this the intended behaviour? It worked in parcel before adding this plugin.

If it is, possibly a friendlier error message?

**Comment by fathyb** [comment]
It works with Parcel because it doesn't do any type-checking (so it doesn't need it). It is kinda intended but the error message could be way better. Feel free to create a PR
