### ISSUE TITLE
Is it possible to use ts-transformer-keys  with parcel?

### ISSUE THREAD

**Issue by Austaras** [fathyb/parcel-plugin-typescript#48]
If it is, is there an example to show me how?

**Comment by TkDodo** [comment]
I tried this today, unsuccessfully :/

The transfomer is picked up, like it should, when specifying the correct field in `tsconfig.json`:

```
  "parcel-plugin-typescript": {
    "transformers": "./config/transformers"
  }
```

`./config/transformers` simply does the following:

```
const keysTransformer = require('ts-transformer-keys/transformer').default
const program = ???

exports.default = function() {
    return {
        before: [keysTransformer(program)],
        after: []
    }
}
```

The problem I ran into was that `keysTransformer` needs to be passed the typescript program, which I don't know how to obtain. I tried to create a `program`, as described here: https://github.com/kimamula/ts-transformer-keys/blob/master/README.md#typescript-api

which resulted in this code:

```
const keysTransformer = require('ts-transformer-keys/transformer').default
const ts = require('typescript')
const tsconfig = require('../tsconfig.json')

const typescript = ts.parseJsonConfigFileContent(tsconfig, ts.sys, './')
const program = ts.createProgram(typescript.fileNames, {})

exports.default = function() {
    return {
        before: [keysTransformer(program)],
        after: []
    }
}
```

everything seems to work, until it crashes with the following stacktrace:

```
Error: TypeError: Cannot read property 'text' of undefined
    at getErrorSpanForNode (node_modules/typescript/lib/typescript.js:8951:40)
    at createDiagnosticForNodeInSourceFile (node_modules/typescript/lib/typescript.js:8870:20)
    at Object.createDiagnosticForNode (node_modules/typescript/lib/typescript.js:8861:16)
    at error (node_modules/typescript/lib/typescript.js:26133:22)
    at resolveExternalModule (node_modules/typescript/lib/typescript.js:27388:25)
    at resolveExternalModuleNameWorker (node_modules/typescript/lib/typescript.js:27324:19)
    at resolveExternalModuleName (node_modules/typescript/lib/typescript.js:27319:20)
    at getTargetOfImportClause (node_modules/typescript/lib/typescript.js:27014:32)
    at getTargetOfAliasDeclaration (node_modules/typescript/lib/typescript.js:27149:28)
    at resolveAlias (node_modules/typescript/lib/typescript.js:27183:30)
    at TypeScriptWorker.<anonymous> (node_modules/parcel-plugin-typescript/build/backend/ipc/worker/index.js:27:19)
```

I don't really have a clue how to proceed from here ... any input would be appreciated!
