### ISSUE TITLE
Paths with prefix @ don't work

### ISSUE THREAD

**Issue by ChristoRibeiro** [fathyb/parcel-plugin-typescript#56]
Hi,

I have tried to put the `@` as prefix on my paths but the module resolution doesn't work anymore. What about you?

```diff
// tsconfig.json

"compilerOptions": {
    "baseUrl": "src",
  },
  "paths": {
+   "@components/*": ["components/*"]
-   "components/*": ["components/*"]
  }
```

```diff
// App.tsx

+ import Hello from "@components/Hello";
- import Hello from "components/Hello";
```

**Comment by ChristoRibeiro** [comment]
Actually, all is fine! It was a typo error in the tsconfig.json that throws the error:

```
➜ yarn start
yarn run v1.5.1
$ parcel public/index.html
Server running at http://localhost:1234
⚠️  Unexpected token ]
    at unexpected (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/json-parser/index.js:121:9)
    at walk (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/json-parser/index.js:104:3)
    at parse_array (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/json-parser/index.js:165:29)
    at walk (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/json-parser/index.js:94:14)
    at parse_object (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/json-parser/index.js:148:33)
    at walk (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/json-parser/index.js:91:14)
    at Object.parse (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/json-parser/index.js:55:16)
    at Object.parse (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/comment-json/lib/parse.js:8:17)
    at Object.<anonymous> (/Users/christophe/Code/dinoo/dinoo-webapp/node_modules/parcel-plugin-typescript/build/backend/config-loader.js:25:37)
    at Generator.next (<anonymous>)
```

The fix:

```diff
// tsconfig.json

  "include": [
-    "app/**/*",
+    "app/**/*"
  ],
```
