### ISSUE TITLE
Failed to fetch when using NPM proxy

### ISSUE THREAD

**Issue by fathyb** [fathyb/parcel-plugin-typescript#6]
Moved from #5, From @llfylwg

> 
> I can not install this , the error :
> 
> ```
> error An unexpected error occurred: "http://npm.jd.com/@babel%2fcode-frame: no such package available".
> info If you think this is a bug, please open a bug report with the information provided in "D:\vue-learn\ts-demo-new\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> Error: http://npm.jd.com/@ngtools%2fwebpack: no such package available
> at Request.params.callback [as _callback] (D:\yarn\lib\cli.js:62098:18)
> at Request.self.callback (D:\yarn\lib\cli.js:123085:22)
> at Request.emit (events.js:159:13)
> at Request. (D:\yarn\lib\cli.js:124068:10)
> at Request.emit (events.js:159:13)
> at IncomingMessage. (D:\yarn\lib\cli.js:123988:12)
> at Object.onceWrapper (events.js:254:19)
> ```

**Comment by fathyb** [comment]
@llfylwg it seems to be your proxy (`http://npm.jd.com`), I'm not familiar with NPM support in China, is there any way you can change or not use the proxy?
